In [1]:
import numpy as np
n1 = np.array([[3,5,2,1],[6,3,9,5],[1,7,4,8]])
print(n1)

[[3 5 2 1]
 [6 3 9 5]
 [1 7 4 8]]


In [2]:
n1.ravel()

array([3, 5, 2, 1, 6, 3, 9, 5, 1, 7, 4, 8])

In [3]:
n1.flatten()

array([3, 5, 2, 1, 6, 3, 9, 5, 1, 7, 4, 8])

* Matrix multiplications

In [4]:
print(n1)

[[3 5 2 1]
 [6 3 9 5]
 [1 7 4 8]]


In [5]:
n2 = np.array([[2,5,5,1],
               [3,8,9,2]])
print(n2)

[[2 5 5 1]
 [3 8 9 2]]


In [6]:
np.transpose(n2)

array([[2, 3],
       [5, 8],
       [5, 9],
       [1, 2]])

In [7]:
np.dot(n1,np.transpose(n2))

array([[ 42,  69],
       [ 77, 133],
       [ 65, 111]])

In [8]:
#3x + 2y + z = 5
#x + y + z = 7
#5x + 7y + 3z = 9

In [9]:
A = np.array([[3,2,1],[1,1,1],[5,7,3]])
print(A)

[[3 2 1]
 [1 1 1]
 [5 7 3]]


In [10]:
X = np.array([['x'],['y'],['z']])
print(X)

[['x']
 ['y']
 ['z']]


In [11]:
B = np.array([[5],[7],[9]])
print(B)

[[5]
 [7]
 [9]]


In [12]:
#A.X = B
#X = A_inv.B

In [13]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.66666667 -0.16666667 -0.16666667]
 [-0.33333333 -0.66666667  0.33333333]
 [-0.33333333  1.83333333 -0.16666667]]


In [14]:
X = np.dot(A_inv,B)
print(X)

[[ 0.66666667]
 [-3.33333333]
 [ 9.66666667]]


In [15]:
np.dot(A,X)

array([[5.],
       [7.],
       [9.]])

In [16]:
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
n1 = np.array([[3,5,2,1],[6,3,9,5],[1,7,4,8]])
print(n1)

[[3 5 2 1]
 [6 3 9 5]
 [1 7 4 8]]


In [20]:
n3 = n1[1:3,1:3].copy()
print(n3)

[[3 9]
 [7 4]]


In [21]:
n3[1,1] = 44

In [22]:
print(n3)

[[ 3  9]
 [ 7 44]]


In [23]:
print(n1)

[[3 5 2 1]
 [6 3 9 5]
 [1 7 4 8]]


Assignment 1 - Working with NumPy


Objective Understand the basics of NumPy, array creation, and manipulation.


Instructions 


Step 1 Install NumPy using
pip install numpy


Step 2 Create a new Python script numpy_assignment.ipynb. Import NumPy and follow these steps:  


1. Create a 1D NumPy array with integers from 1 to 20. Perform the following operations:  
  a. Calculate the sum, mean, median, and standard deviation of the elements in the array.  
  b. Find the indices of elements greater than 10 in the array.  


2. Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.  
  a. Print the array.  
  b. Find the transpose of the array.  
  c. Calculate the row-wise and column-wise sums of the array.  


3. Create two 3 X 3 arrays filled with random integers between 1 and 20.  
  a. Perform element-wise addition, subtraction, and multiplication.  
  b. Compute the dot product of the two arrays.  


4. Reshape a 1D array of size 12 into a 3 X 4 2D array and slice the first two rows and last two columns.  


In [24]:
import numpy as np

# --------------------------
# 1. 1D Array
# --------------------------
arr1 = np.arange(1, 21)

# a. Statistics
print("1D Array:", arr1)
print("Sum:", np.sum(arr1))
print("Mean:", np.mean(arr1))
print("Median:", np.median(arr1))
print("Standard Deviation:", np.std(arr1))

# b. Indices of elements > 10
print("Indices > 10:", np.where(arr1 > 10)[0])

# --------------------------
# 2. 2D Array (4x4)
# --------------------------
arr2 = np.arange(1, 17).reshape(4, 4)
print("\n2D Array (4x4):\n", arr2)

# a. Transpose
print("Transpose:\n", arr2.T)

# b. Row-wise and column-wise sums
print("Row sums:", np.sum(arr2, axis=1))
print("Column sums:", np.sum(arr2, axis=0))

# --------------------------
# 3. Random 3x3 Arrays
# --------------------------
arr3_a = np.random.randint(1, 21, (3, 3))
arr3_b = np.random.randint(1, 21, (3, 3))

print("\nArray A:\n", arr3_a)
print("Array B:\n", arr3_b)

# a. Element-wise operations
print("Addition:\n", arr3_a + arr3_b)
print("Subtraction:\n", arr3_a - arr3_b)
print("Multiplication:\n", arr3_a * arr3_b)

# b. Dot product
print("Dot Product:\n", np.dot(arr3_a, arr3_b))

# --------------------------
# 4. Reshape and Slice
# --------------------------
arr4 = np.arange(1, 13).reshape(3, 4)
print("\nReshaped 3x4 Array:\n", arr4)
print("Sliced (first 2 rows, last 2 cols):\n", arr4[:2, -2:])


1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398
Indices > 10: [10 11 12 13 14 15 16 17 18 19]

2D Array (4x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row sums: [10 26 42 58]
Column sums: [28 32 36 40]

Array A:
 [[17  9 13]
 [ 7  5 13]
 [ 2 19  4]]
Array B:
 [[13 17  1]
 [13  7 19]
 [18  6  5]]
Addition:
 [[30 26 14]
 [20 12 32]
 [20 25  9]]
Subtraction:
 [[  4  -8  12]
 [ -6  -2  -6]
 [-16  13  -1]]
Multiplication:
 [[221 153  13]
 [ 91  35 247]
 [ 36 114  20]]
Dot Product:
 [[572 430 253]
 [390 232 167]
 [345 191 383]]

Reshaped 3x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sliced (first 2 rows, last 2 cols):
 [[3 4]
 [7 8]]
